### ISSUE TITLE
Nile's Idea ?

### ISSUE THREAD

**Issue by sylver-john** [gitsummore/nile.js#33]
Hello,

Could you tell me if you got the idea of Nile and the Nile's landing page from this project : https://github.com/pulsardev/netsix (and it landing https://mmorainville.github.io/netsix-gh-pages). We created an electron app using WebRTC to stream videos.

Regards

**Comment by kbbqiu** [comment]
@sylver-john Hey! 

Have not seen this project before and it actually looks a little more complete and less experimental than Nile.js. About 2 months ago, we stumbled upon webTorrent and got really interested in how the technology works. After diving into the issues posts, the next logical step was to use webTorrent to stream live video. Feross even has a small portion in the webTorrent documentation dedicated to "possibilities of live streaming." We basically implemented a simple approach to augment webTorrent. 

As for the landing page, we just derived it form the name. Simple put, what the library does is to convert one video stream and distribute it to many streams, eventually ending up on a huge network, such as--the ocean. We originally had ideas like naming it the Hudson, or Panama. But Nile.js ended up sticking. 

And the issue with netsix. I haven't really looked through the codebase, but I am guessing that you will be hard limited to about 20-30 connections simply based on webRTC's capabilities of streaming video right? Since, we are using webtorrents and the only thing being propagated down the chain of webRTC connections is a magnet in the form of string, there is virtually no http overdraft on client and server. Theoretically Nile.js could allow for infinite number of p2p connections.

Hope that answers everything! Lemme know, I'll close the issue tomorrow if you haven't responded!

**Comment by mmorainville** [comment]
Hi @kbbqiu,

Thanks for replying! I'm working on Netsix with @sylver-john and I would like to clarify some points.
First, Netsix is still quite experimental but it's indeed more oriented toward end-users.
We also didn't want to use torrent at all at first, because the goal was really just to have a friend-to-friend sharing rather than peer-to-peer, so that someone could stream a video file of a remote friend in a secure and "undetectable" way.

So both projects seem indeed quite different but in a way that they could maybe profit to each other. Nile.js looks indeed more like a library/tool so maybe if we decide someday to implement torrenting in Netsix, we may use it :-). For now we are indeed limited in the amount of connections we can make but as I said, it's not a big deal in our use case, as it would already be good if someone could stream a video file to 5-6 friends simultaneously (also because in the end the sender's upstream throughput will be limited).

And if I understand correctly, you also use WebRTC in the same it's use on feross' WebTorrent, which is only for transmitting the magnet, whereas in our case the entire file goes through it chunk by chunk.

So anyway I'm glad we clarified this and we look forward to the success of your project!

Regards,
M.
